from __future__ import annotations

from collections.abc import Sequence
from dataclasses import dataclass

import torch
from torch import Tensor
from torch.nn import functional as F

from tokenizer import FEEDBACK_TO_SYMBOL, FEEDBACK_TOKEN, GUESS_TOKEN
from tokenizer_v2 import POLICY_TOKEN, TOKEN_TO_ID, VOCABULARY_SIZE, encode
from wordle import GREEN, _validate_word, score_guess

MAX_TURNS = 6
WORD_LENGTH = 5
GROUP_SIZE = 8
MAX_ACTIONS = MAX_TURNS * WORD_LENGTH


@dataclass
class TrajectoryBatch:
    """Padded model inputs and generated-action metadata for complete games."""

    inputs: Tensor
    positions: Tensor
    actions: Tensor
    masks: Tensor
    valid: Tensor
    old_token_logps: Tensor
    rewards: Tensor
    won: Tensor
    attempts: Tensor
    secrets: tuple[str, ...]
    guesses: tuple[tuple[str, ...], ...]


class LegalWordDecoder:
    """Batched trie lookup for legal dictionary prefixes on a chosen device."""

    def __init__(self, words: Sequence[str], device: torch.device | str = "cpu") -> None:
        normalized = tuple(dict.fromkeys(_validate_word(word, "allowed word") for word in words))
        if not normalized:
            raise ValueError("at least one legal word is required")

        # Node 0 is the root; each row maps a letter to its child or -1.
        children: list[list[int]] = [[-1] * 26]
        for word in normalized:
            node = 0
            for letter in word:
                letter_id = ord(letter) - ord("a")
                child = children[node][letter_id]
                if child < 0:
                    child = len(children)
                    children[node][letter_id] = child
                    children.append([-1] * 26)
                node = child

        self.words = normalized
        self.child_nodes = torch.tensor(children, dtype=torch.long, device=device)
        self.device = self.child_nodes.device
        self.legal_letters = self.child_nodes.ge(0)

    def legal_mask(self, node_ids: Tensor) -> Tensor:
        """Return a ``[..., 26]`` mask of legal next letters for trie nodes."""
        return self.legal_letters[node_ids]

    def advance(self, node_ids: Tensor, letter_ids: Tensor) -> Tensor:
        """Advance a batch of nodes using letter IDs, without scalar indexing."""
        return self.child_nodes[node_ids, letter_ids]


@torch.no_grad()
def sample_games(
    model,
    secrets: Sequence[str],
    decoder: LegalWordDecoder,
    group_size: int = GROUP_SIZE,
    *,
    histories: Sequence[Sequence[tuple[str, str]]] | None = None,
) -> TrajectoryBatch:
    """Sample independent, replacement-enabled full Wordle continuations.

    Supplied histories are policy-visible evidence and count toward the six-turn
    game limit, but only letters generated by this call contribute to action
    likelihoods. Secrets are used only by the environment to verify feedback.
    """
    if group_size < 1:
        raise ValueError("group_size must be positive")
    if not secrets:
        raise ValueError("at least one secret is required")

    normalized_secrets = tuple(_validate_word(secret, "secret") for secret in secrets)
    allowed = set(decoder.words)
    if any(secret not in allowed for secret in normalized_secrets):
        raise ValueError("every secret must be present in the legal word list")

    if histories is None:
        normalized_histories = ((),) * len(normalized_secrets)
    else:
        if len(histories) != len(normalized_secrets):
            raise ValueError("histories must have the same length as secrets")
        checked_histories: list[tuple[tuple[str, str], ...]] = []
        for secret, history in zip(normalized_secrets, histories):
            if len(history) > MAX_TURNS - 1:
                raise ValueError("history depth must be between zero and five")
            checked_history: list[tuple[str, str]] = []
            for entry in history:
                if (
                    not isinstance(entry, Sequence)
                    or isinstance(entry, (str, bytes))
                    or len(entry) != 2
                ):
                    raise ValueError("each history entry must contain a guess and feedback")
                guess = _validate_word(entry[0], "history guess")
                feedback = entry[1]
                if guess not in allowed:
                    raise ValueError("every history guess must be present in the legal word list")
                expected_feedback = score_guess(secret, guess)
                if feedback != expected_feedback:
                    raise ValueError("history feedback must match the secret and guess")
                if expected_feedback == GREEN * WORD_LENGTH:
                    raise ValueError("history must not contain a solved guess")
                checked_history.append((guess, feedback))
            checked_histories.append(tuple(checked_history))
        normalized_histories = tuple(checked_histories)

    try:
        model_device = next(model.parameters()).device
    except (AttributeError, StopIteration):
        model_device = decoder.device
    if torch.device(model_device) != decoder.device:
        raise ValueError("model and legal-word decoder must use the same device")
    device = decoder.device

    group_count = len(normalized_secrets)
    row_count = group_count * group_size
    flat_secrets = tuple(secret for secret in normalized_secrets for _ in range(group_size))
    flat_histories = tuple(
        history for history in normalized_histories for _ in range(group_size)
    )
    feedback_token = TOKEN_TO_ID[FEEDBACK_TOKEN]
    guess_token = TOKEN_TO_ID[GUESS_TOKEN]
    base_sequences: list[list[int]] = []
    for history in normalized_histories:
        sequence = encode(POLICY_TOKEN + GUESS_TOKEN)
        for guess, feedback in history:
            sequence.extend(ord(letter) - ord("a") for letter in guess)
            encoded_feedback = [TOKEN_TO_ID[FEEDBACK_TO_SYMBOL[mark]] for mark in feedback]
            sequence.extend((feedback_token, *encoded_feedback, guess_token))
        base_sequences.append(sequence)

    sequences = [
        base_sequences[row // group_size].copy() for row in range(row_count)
    ]
    guesses: list[list[str]] = [
        [guess for guess, _ in history] for history in flat_histories
    ]
    reward_values = [0.0] * row_count
    won_values = [False] * row_count
    attempt_values = [len(history) for history in flat_histories]

    positions = torch.zeros((row_count, MAX_ACTIONS), dtype=torch.long, device=device)
    actions = torch.zeros((row_count, MAX_ACTIONS), dtype=torch.long, device=device)
    masks = torch.ones(
        (row_count, MAX_ACTIONS, VOCABULARY_SIZE), dtype=torch.bool, device=device
    )
    valid = torch.zeros((row_count, MAX_ACTIONS), dtype=torch.bool, device=device)
    old_token_logps = torch.zeros(
        (row_count, MAX_ACTIONS), dtype=torch.float32, device=device
    )

    for turn in range(MAX_TURNS):
        # A row's attempt count is its absolute turn. Therefore every member of
        # this bucket has the same prompt length, even when starting histories
        # have different depths.
        active_rows = [
            row
            for row, attempts in enumerate(attempt_values)
            if attempts == turn and not won_values[row]
        ]
        if not active_rows:
            continue

        prefix_length = len(sequences[active_rows[0]])
        if any(len(sequences[row]) != prefix_length for row in active_rows):
            raise RuntimeError("active trajectories do not share the current turn")
        row_ids = torch.tensor(active_rows, dtype=torch.long, device=device)
        prefix = torch.tensor(
            [sequences[row] for row in active_rows], dtype=torch.long, device=device
        )
        turn_inputs = torch.empty(
            (len(active_rows), prefix_length + WORD_LENGTH), dtype=torch.long, device=device
        )
        turn_inputs[:, :prefix_length] = prefix
        node_ids = torch.zeros(len(active_rows), dtype=torch.long, device=device)
        sampled_letters: list[Tensor] = []

        for offset in range(WORD_LENGTH):
            logits = model(turn_inputs[:, : prefix_length + offset])[:, -1, :]
            if logits.shape[-1] != VOCABULARY_SIZE:
                raise ValueError(
                    f"model vocabulary has {logits.shape[-1]} tokens; expected {VOCABULARY_SIZE}"
                )
            legal = decoder.legal_mask(node_ids)
            constrained = logits[:, :26].masked_fill(~legal, -torch.inf)
            log_distribution = F.log_softmax(constrained, dim=-1)
            letter_ids = torch.multinomial(log_distribution.exp(), num_samples=1).squeeze(1)
            turn_inputs[:, prefix_length + offset] = letter_ids

            action_column = turn * WORD_LENGTH + offset
            positions[row_ids, action_column] = prefix_length - 1 + offset
            actions[row_ids, action_column] = letter_ids
            valid[row_ids, action_column] = True
            masks[row_ids, action_column, :] = False
            masks[row_ids, action_column, :26] = legal

            sampled_letters.append(letter_ids)
            old_token_logps[row_ids, action_column] = log_distribution.gather(
                1, letter_ids[:, None]
            ).squeeze(1)
            node_ids = decoder.advance(node_ids, letter_ids)

        turn_actions = torch.stack(sampled_letters, dim=1)

        words_this_turn = tuple(
            "".join(chr(letter + ord("a")) for letter in row)
            for row in turn_actions.tolist()
        )
        for row, guess in zip(active_rows, words_this_turn):
            guesses[row].append(guess)
            sequences[row].extend(ord(letter) - ord("a") for letter in guess)
            attempt = turn + 1
            attempt_values[row] = attempt
            feedback = score_guess(flat_secrets[row], guess)
            if feedback == GREEN * WORD_LENGTH:
                won_values[row] = True
                reward_values[row] = float(7 - attempt)
                continue

            if turn + 1 < MAX_TURNS:
                encoded_feedback = [
                    TOKEN_TO_ID[FEEDBACK_TO_SYMBOL[mark]] for mark in feedback
                ]
                sequences[row].extend((feedback_token, *encoded_feedback, guess_token))

    max_length = max(map(len, sequences))
    if max_length > 67:
        raise RuntimeError(f"v2 game input length {max_length} exceeds 67 tokens")
    inputs = torch.zeros((row_count, max_length), dtype=torch.long, device=device)
    for row, sequence in enumerate(sequences):
        inputs[row, : len(sequence)] = torch.tensor(sequence, dtype=torch.long, device=device)

    return TrajectoryBatch(
        inputs=inputs,
        positions=positions,
        actions=actions,
        masks=masks,
        valid=valid,
        old_token_logps=old_token_logps,
        rewards=torch.tensor(reward_values, dtype=torch.float32, device=device).view(
            group_count, group_size
        ),
        won=torch.tensor(won_values, dtype=torch.bool, device=device).view(
            group_count, group_size
        ),
        attempts=torch.tensor(attempt_values, dtype=torch.long, device=device).view(
            group_count, group_size
        ),
        secrets=normalized_secrets,
        guesses=tuple(tuple(row_guesses) for row_guesses in guesses),
    )
